export const SET_SNACKBAR_MESSAGE = "SET_SNACKBAR_MESSAGE";
export const SET_LOADING = "SET_LOADING";
export const SET_DISCOVER_MOVIE_DATA = "SET_DISCOVER_MOVIE_DATA";
export const SET_OMDB_SEARCH_RESULTS = "SET_OMDB_SEARCH_RESULTS";
export const SET_DISCOVER_TMDB_MOVIE = "SET_DISCOVER_TMDB_MOVIE";
export const SET_LOGIN_DIALOG_MODE = "SET_LOGIN_DIALOG_MODE";
export const SET_USER = "SET_USER";
export const SET_FAVORITES = "SET_FAVORITES";
